### ISSUE TITLE
Bug？When I received a 10 KB byte string

### ISSUE THREAD

**Issue by kingofalpha** [espressif/esp-mqtt#105]

**Comment by david-cermak** [comment]
Hi @kingofalpha ,

which version of esp-mqtt you using? there indeed were issues with receiving (and sending) message longer that configured buffer size, but this is resolved in latest `idf` branch. Please note that the data will come within multiple data events.

**Comment by david-cermak** [comment]
Closing for no recent updates. Feel free to reopen!
