### ISSUE TITLE
This implementation is useless (IDFGH-939)

### ISSUE THREAD

**Issue by bojczmac** [espressif/esp-mqtt#112]
Try to send 10 mqtt message with 50ms interval. This client received only 3 od 4 messages.

**Comment by david-cermak** [comment]
I believe you've just tried the code on master branch of esp-mqtt? Indeed there is an issue with retained messages, which was fixed on `idf` branch (this branch is referenced from esp-idf).

Will merge the `idf` branch to `master` soon.

**Comment by bojczmac** [comment]
Thank you for the information, I will check it today afternoon.

**Comment by bojczmac** [comment]
You've right, it works on idf branch. 25 messages sent with delay 10ms between and 25 messages received. Currently I made backport for IDF 3.1.3, because I saw that esp-mqtt will be released with IDF 3.2
