### ISSUE TITLE
BIG Memory leak in esp-mqtt outbox_cleanup() (IDFGH-2558)  (IDFGH-2598)

### ISSUE THREAD

**Issue by eespi** [espressif/esp-mqtt#147]
I'm reposting here a problem i found in the library. 
In esp-idf issue tracker the ticket it has not taken into consideration yet.

[(https://github.com/espressif/esp-idf/issues/4643)]

**Comment by david-cermak** [comment]
Hi @eespi 

Thanks for the bug report!
It's been recorded in the bug-tracker and the fix should be available shortly after the changes get reviewed.
