### ISSUE TITLE
MQTT_API_UNLOCK() is not called in function esp_mqtt_client_subscribe() (IDFGH-2650)

### ISSUE THREAD

**Issue by umer-ilyas** [espressif/esp-mqtt#150]
in file **mqtt_client.c** at **line1463** functions (`esp_mqtt_client_subscribe`) is returning without calling MQTT_API_UNLOCK(client);

Commit: d5e915296ebcf57d167c0410db8dd9ec746b95c5

[unlock_semaphore_here.zip](https://github.com/espressif/esp-mqtt/files/4165625/unlock_semaphore_here.zip)

**Comment by david-cermak** [comment]
@umer-ilyas Thanks for reporting the issue and posting the fix. Indeed this branch missing unlocking the mutex. Will be fixed soon!
