### ISSUE TITLE
URL's query-string portion is getting cut off. (IDFGH-3565)

### ISSUE THREAD

**Issue by klisevich** [espressif/esp-mqtt#161]
Hi!
I'm using MQTT over WebSocket in order to connect to amazon's endpoint with [SigV4 pre-signed URL](https://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html). There is an issue with ignoring query-string in mqtt_client.c:764 
`client->config->path = create_string(uri + puri.field_data[UF_PATH].off, puri.field_data[UF_PATH].len);`
I'm getting path like `wss://<endpoint>.iot.<region>.amazonaws.com/mqtt` instead of `wss://<endpoint>.iot.<region>.amazonaws.com/mqtt?Action=ListUsers&Version=2010-05-08`.
What would you advise?

**Comment by ESP-Marius** [comment]
Hi @klisevich

Thanks for making us aware of this issue. I've created a MR to allow the query part of the uri to be added to the path.  We'll update this issue when it's been merged.
