### ISSUE TITLE
client subscribe checking (IDFGH-3683)

### ISSUE THREAD

**Issue by gulkanguner** [espressif/esp-mqtt#162]
Hi,
In my project I subscribe more than one topics. However I have subscribed  succesfully, I have realise that somehow my esp32 is unsubscribed the topic.  For this reason I want to check my subscribed topics. Is there any way to check this?

**Comment by ESP-Marius** [comment]
Hi,

There is no way to check which topics you are subscribed to on the client side. I would suggest you take a look at the logs of your broker/server. That should help you figure out if your esp32 unsubscribed to topics.

**Comment by david-cermak** [comment]
Closing as the question is answered.
