### ISSUE TITLE
Unbalance lock in esp_mqtt_client_stop error path (IDFGH-4226)

### ISSUE THREAD

**Issue by AxelLin** [espressif/esp-mqtt#173]
The commit 5e17dcaeb257f847386478119935ecd360f47377 missed an MQTT_API_UNLOCK call before return ESP_FAIL
so it returns error with the lock held.

**Comment by AxelLin** [comment]
I sent the fix in Mqtt fixes #174

**Comment by david-cermak** [comment]
Fixed via https://github.com/espressif/esp-mqtt/commit/845c2a3a1e112af5dbe5f3a9ee8f6adb92a03757 
Thank you @AxelLin !
