### ISSUE TITLE
Feature Request: Access retained flag on received message (IDFGH-5297)

### ISSUE THREAD

**Issue by calkoe** [espressif/esp-mqtt#193]
@david-cermak

Feature Request:

It would be awesome to be able to check if a received message was a retained one and may be old.
I'm controlling door locks via MQTT and this would be very important to me.

```cpp
typedef struct {
     ...
     bool retained; /*!< true indicates the message was retained and may be old. */
     ...
} esp_mqtt_event_handle_t
```

![image](https://user-images.githubusercontent.com/26646066/119145191-b3643580-ba49-11eb-81fa-f8ce4f5e7d2d.png)

Thanks!

**Comment by david-cermak** [comment]
Thanks for this useful suggestion.

You can evaluate this feature applying the below patch:
[Add-support-for-Retain-flag-in-messages-posted-by-ev.patch.txt](https://github.com/espressif/esp-mqtt/files/6531264/Add-support-for-Retain-flag-in-messages-posted-by-ev.patch.txt)
