### ISSUE TITLE
Check if messages are waiting in outbox queue (IDFGH-5351)

### ISSUE THREAD

**Issue by poerob** [espressif/esp-mqtt#197]
Hello,
in a project, an esp32 must go to deep sleep from time to time.
Before i activate deep sleep, i'd like to make sure there are no message on the mqtt outbox queue, which would be discarded if i enter deep sleep without waiting for them to be send. 

How can i check if the message outbox queue is empty and i can safely enter deep sleep?

Thanks in advance!

**Comment by david-cermak** [comment]
Hi @poerob 

There's an API which checks the outbox size: `esp_mqtt_client_get_outbox_size()`
This should be `0` if no message queued.

**Comment by poerob** [comment]
Oh, how could i overlook this... thank you!
