### ISSUE TITLE
Access QoS and dup on receiving events (IDFGH-5802)

### ISSUE THREAD

**Issue by bertmelis** [espressif/esp-mqtt#200]
Is it possible to get the QoS, dup-flag and retain-flag when receiving messages or subacks?

I can't find any docs on this. Happy to create a PR if not yet implemented. (note: I did not try to implement yet)

**Comment by david-cermak** [comment]
@bertmelis Only the retain flag is available in the data event:

https://github.com/espressif/esp-mqtt/blob/master/mqtt_client.c#L958

[qos and dup flags](https://github.com/espressif/esp-mqtt/blob/master/lib/include/mqtt_msg.h#L113-L124) could be added in a similar way. PRs welcome :+1:

**Comment by bertmelis** [comment]
While implementing I overlooked something I also wanted: the payload from the SUBACK message.
This payload contains the maximum granted qos level of the subscribe, or 0xF for failure.

OK to put in the same PR?

**Comment by david-cermak** [comment]
> OK to put in the same PR?

Absolutely, but please make it a separate commit.
