### ISSUE TITLE
esp_mqtt_connect: mqtt_message_receive() returned -1 , MQTT connect failed (IDFGH-5813)

### ISSUE THREAD

**Issue by torntrousers** [espressif/esp-mqtt#201]
I'm trying to use esp-mqtt with mqtt over websockets connecting to AWS IoT with a custom authorizer, but it fails to connect. The request gets in to AWS ok and I can see the custom authoriser has run and and authorised the connection. On the ESP32 debug logs I get:

```
E (302789) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=119
E (302790) MQTT_CLIENT: esp_mqtt_connect: mqtt_message_receive() returned -1
E (302794) MQTT_CLIENT: MQTT connect failed
```

Any tips on how I could debug this ?

TIA!

**Comment by euripedesrocha** [comment]
Hi @torntrousers, could you please run your code with:

```
 esp_log_level_set("MQTT_CLIENT", ESP_LOG_DEBUG);
```
and share the logs with us.

**Comment by torntrousers** [comment]
Sure, sorry its going to take a couple of days to get back to that code...

**Comment by torntrousers** [comment]
I'm sorry but I can't find where I have put the code for testing this, so I will close for now.
