### ISSUE TITLE
Streaming API (IDFGH-6052)

### ISSUE THREAD

**Issue by galah92** [espressif/esp-mqtt#209]
Hi,

My ESP-based application fetch data from SPI and send it via MQTT. I'd like to lower the number of sent messages, and technically able to concatenate the data to larger messages. But, I don't have enough free ram for that.

Can we add API for stream a message (with known size), so that I could publish a single message in chunks?

**Comment by david-cermak** [comment]
Hi @galah92 

Thanks for this feature request! It really makes sense to add this stream API, but could also bring about some trouble.
1) This could only work for qos=0 messages if we want to store them in the outbox (and store we must, per spec)
2) Also, this could complicate the current implementation, as we have to silence all possible acknowledges, pings and re-sends when streaming of one message is active (and not only silence, but also queue, i.e. save for sending later)

On the other hand, from your use-case (and all possible practical uses of these APIs) I assume that it could be just enough to suspend the client while sending the partial data. This is easy to implement (a bit dangerous though, as we keep the client locked between sends! and rely on users to be careful and use the API correctly).

I created a simple WIP version of this functionality. Is this something that would help you to publish one message in chunks?
[Client-Add-simple-stream-API.patch.txt](https://github.com/espressif/esp-mqtt/files/7485993/Client-Add-simple-stream-API.patch.txt)

**Comment by david-cermak** [comment]
Closing for short of feedback. The patch above works but has to be used in consideration, so better not merging this to the official  master branch.
