### ISSUE TITLE
Question: event: running post MQTT_EVENTS: 6 with handler.... and context .... on loop ... (IDFGH-6146)

### ISSUE THREAD

**Issue by goofy2k** [espressif/esp-mqtt#210]
Hi, just a question.  I see messages as indicated in the issue title in my logs.  What does it mean?

**Comment by AndriiFilippov** [comment]
Hi, @goofy2k ! 

This is a debugging log from the esp_event. 
https://github.com/espressif/esp-idf/blob/master/components/esp_event/esp_event.c#L127

**Comment by goofy2k** [comment]
OK, thanks Andrii,  so there is nothing wrong :-). I just have to lower the
logging setting to less than DEBUG.

Op do 4 nov. 2021 16:24 schreef Andrii ***@***.***>:

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, you could also create a post on our forum at https://esp32.com, thanks.

**Comment by david-cermak** [comment]
@goofy2k I agree with @Alvin1Zhang , please prefer the forum for basic/general questions about IDF/ESP32(-X).

anyway, I think you're satisfied with @AndriiFilippov 's answers, so closing this issue.
