### ISSUE TITLE
How to get this work with TinyGSM (IDFGH-6243)

### ISSUE THREAD

**Issue by garudaonekh** [espressif/esp-mqtt#212]
Hello,
My esp32 needs to connect to the Internet via GPRS 2G so we use TinyGSm but we have trouble integrating it with ESP-MQTT. Any suggestion?

Thanks;

**Comment by david-cermak** [comment]
@garudaonekh Have you checked this example https://github.com/espressif/esp-idf/tree/master/examples/protocols/pppos_client ?

It seems that TinyGSM connects using PPP mode, too, so should really work the same way as in the example above.

**Comment by garudaonekh** [comment]
yes, this should work. However,i cannot get it work with TTGO Sim800. However, I got another adapted one working. Thanks
