### ISSUE TITLE
Does ESP-MQTT support MQTT v5? (IDFGH-6538)

### ISSUE THREAD

**Issue by misterzirillo** [espressif/esp-mqtt#216]
Digging around in the docs I don't see mention of the protocol version.

https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html

**Comment by euripedesrocha** [comment]
Hi @misterzirillo,
we don't support MQTT v5. 
We do have it planned for the future, but it's not likely to happen anytime soon.

**Comment by misterzirillo** [comment]
Thanks for the update!
