### ISSUE TITLE
CONFIG_MQTT_CUSTOM_OUTBOX usage (IDFGH-6554)

### ISSUE THREAD

**Issue by someburner** [espressif/esp-mqtt#217]
Using the latest esp-idf master branch and setting CONFIG_MQTT_CUSTOM_OUTBOX=y, I am unable to get a project to link with custom outbox. I admit I'm not very accustomed to cmake so perhaps there is some setting I need to use to get it to link?

Basically I just added a copy of `mqtt_outbox.c` and `mqtt_outbox.h` to my project but when I build I get link errors for all the outbox methods.

Perhaps if CONFIG_MQTT_CUSTOM_OUTBOX is defined, all the outbox methods in `mqtt_client.c` need extern definitions?

**Comment by david-cermak** [comment]
Hi @someburner 

Yes, it has something to do with the way cmake builds IDF, the outbox implementation needs to be added to the `mqtt` component (static lib) sources. Here's how you can do it from your Makefile:
```cmake
# Your project name
project(...)

# Add custom outbox imple to mqtt component
idf_component_get_property(mqtt mqtt COMPONENT_LIB)
set_property(TARGET ${mqtt} PROPERTY SOURCES ${PROJECT_DIR}/main/custom_outbox.c APPEND)
```

**Comment by someburner** [comment]
Thank you I will try this out. I would suggest this be documented somewhere.

**Comment by someburner** [comment]
Thanks @david-cermak !
