### ISSUE TITLE
esp_mqtt_client_publish bug with large data (IDFGH-7091)

### ISSUE THREAD

**Issue by ChristophRh** [espressif/esp-mqtt#219]
The description of 
`esp_mqtt_client_publish()`
states
`* @param len       data length, if set to 0, length is calculated from payload string`
That is **not** true for payload larger than the configured MQTT buffer size.

**with QoS 0:**
the Broker receives only the first part and discards it

**with QoS 1:**
the Broker receives a faulty second part and the connection is reset

The bug seems to be in[ line 1838](https://github.com/espressif/esp-mqtt/blob/4874bab35659bd2301e65fd849f6559d7380d4f1/mqtt_client.c#L1838)
`int remaining_len = len;`
must be changed to 
`int remaining_len = strlen(data);`
Otherwise the remaining length is initialized with 0, which is definitely not the case for large payloads.

Another option is to not allow parameter `len` to be `0`, but always the payload length.

**Comment by euripedesrocha** [comment]
Hi @ChristophRh While I investigate the issue, could you please inform the version of idf you are using?

**Comment by ChristophRh** [comment]
I'm using esp-idf version 4.4.0

**Comment by euripedesrocha** [comment]
Hi @ChristophRh, this is already fixed, see issue #214, it will be available in idf 4.4.0 soon.

**Comment by ChristophRh** [comment]
Okay thanks!
