### ISSUE TITLE
[BUG] Use AT command AT+MQTTCONN return ERROR code

### ISSUE THREAD

**Issue by iAoe444** [espressif/esp-mqtt#221]
## Problems encountered

Use the AT command `AT+MQTTCONN` to return the error ERROR, the error code is `0x600B`

## Problematic version

Compiled esp-at version: the current latest version `16236bc`

## The error LOG is as follows

```
all parameters are ready[0;33mW (561901) MQTT_CLIENT: Transport config set, but overridden by scheme from URI: transport = 1, uri scheme = mqtt[0m
[0;33mW (561902) MQTT_CLIENT: Client asked to stop, but was not started[0m
[0;31mE (561909) MQTT_CLIENT: Client was not initialized[0m
[at-mqtt]error code:0x600B[at-mqtt]error code:0x6030
```

## Personal debug process

1. By adding printf log, it is found that the problem occurs in the return of line 340 of mqtt_client.c
 
```
  if (cfg->uri && user_cfg->transport) {
      ESP_LOGW(TAG, "Transport config set, but overridden by scheme from URI: transport = %d, uri scheme = %s", user_cfg->transport, cfg->scheme);
      ret = ESP_ERR_INVALID_ARG;
  }

  return ret;
```

at this time, cfg->uri && user_cfg->transport is judged to be true, resulting in an unsuccessful mqtt creation and an error. By looking at the code, I personally think that `cfg->uri && user_cfg->transport` will also return true in the correct situation. Finally, ESP_ERR_INVALID_ARG will be returned, causing AT+MQTTCONN to return an error

2. I have burned the code of `v2.2.0.0_esp32` before, and found that there is no such problem, so I looked at the modifications made between this time period and found that the code was merged in `1d10608`, and the previous code fixed return is ESP_OK , so there is no problem before `v2.2.0.0_esp32`, the code after this has this problem

3. So I personally think this is a bug, but it may also be a problem in my own use process

**Comment by ustccw** [comment]
@iAoe444 esp-at project has already fixed this in a workaround way several weeks ago. could you please try with the latest esp-at firmware.

**Comment by ustccw** [comment]
it should get fixed on https://github.com/espressif/esp-at/commit/ed9e3e7f56e63dba55a2db80e583ebb99df09bae
