### ISSUE TITLE
Make `MQTT_POLL_READ_TIMEOUT_MS` configurable through `menuconfig/sdkconfig` (IDFGH-9196)

### ISSUE THREAD

**Issue by ItayDumayVayyar** [espressif/esp-mqtt#245]
Hey, I have implemented my own [`MQTT` outbox](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-mqtt-custom-outbox) for storing persistent messages in NVS. But I encountered a problem. 
In `esp_mqtt_task()` the main logic is to ask the outbox for an item, transmit it, and then poll read for a potential ACK.  
https://github.com/espressif/esp-mqtt/blob/bb9c8af9d552b608dd3aabf9617bde757a538ebe/mqtt_client.c#L1562-L1568

It appears that `esp_transport_poll_read()` is utilized with a fixed value for `MQTT_POLL_READ_TIMEOUT_MS`, currently set at 1 second. This means that using `esp_mqtt_client_enqueue()` would result in a slow message rate due to the dependency on the timeout period or receipt of an ACK before requesting the next message from the outbox.

**Comment by euripedesrocha** [comment]
Hi @ItayDumayVayyar, thanks for the suggestion. I'm working on this feature, it should be available soon.

**Comment by ItayDumayVayyar** [comment]
> Hi @ItayDumayVayyar, thanks for the suggestion. I'm working on this feature, it should be available soon.

Great, thanks! Can you estimate in what ESP-IDF version this change will be included?
