### ISSUE TITLE
printf nano formatting and using "%zu" in debug log messages (IDFGH-9208)

### ISSUE THREAD

**Issue by kriegste** [espressif/esp-mqtt#246]
In the debug log messages %zu is used almost always. However, when printf nano formatting is enabled, this does not display a number, but just "zu".

Example:
`ESP_LOGD(TAG, "Get data len= %zu, topic len=%zu, total_data: %d offset: %zu", msg_data_len, msg_topic_len, client->event.total_data_len, msg_data_offset);`
https://github.com/espressif/esp-mqtt/blob/master/mqtt_client.c#L1047

Result:
> MQTT_CLIENT: Get data len= zu, topic len=zu, total_data: 6 offset: zu

IDF 4.4.3

**Comment by euripedesrocha** [comment]
Hi @kriegste, thanks for reporting. This will be fixed soon.
