### ISSUE TITLE
TCP_NODELAY (IDFGH-13350)

### ISSUE THREAD

**Issue by Totrasmek** [espressif/esp-mqtt#282]
Hey there, is there a way I can turn off nagle's algorithm for my mqtt connections? It seems like this isn't exposed at the transport level.
Thanks.

**Comment by euripedesrocha** [comment]
Hi @Totrasmek, you are correct that it is not possible at the moment to do it. I'll add a new API to tcp_transport to allow to apply sock options to the open socket. 

While this isn't available, the workaround is to provide your implementation of custom transport that have the required configuration and use it in the mqtt client.

**Comment by Totrasmek** [comment]
That is great news. Thanks @euripedesrocha. For our implementation we wikl make a custom transport.
