### ISSUE TITLE
Not connecting to Local Mosca SSL Broker

### ISSUE THREAD

**Issue by Kasuhikdas** [espressif/esp-mqtt#41]
Mosca SSL Broker is working fine with mqtt client.But ESP32 not connecting to it.
 const esp_mqtt_client_config_t mqtt_cfg = {
        .uri = "mqtts://192.168.43.187",
        .port = "8883",
        .event_handle = mqtt_event_handler,
        .cert_pem = (const char *)ca_crt_start,
        .transport = MQTT_TRANSPORT_OVER_SSL,
        .lwt_topic = "Death",
        .lwt_msg = "Device is Disconnected",
    };
this is the config.
and output is 
I (3107) event: sta ip: 192.168.43.114, mask: 255.255.255.0, gw: 192.168.43.1
I (3107) MQTTS_SAMPLE: [APP] Free memory: 239004 bytes
I (3107) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (3887) MQTT_CLIENT: Sending MQTT CONNECT message, type: 1, id: 0000
E (3897) MQTT_CLIENT: Error network response
I (3897) MQTT_CLIENT: Error MQTT Connected
I (3897) MQTT_CLIENT: Reconnect after 10000 ms
I (3897) MQTTS_SAMPLE: MQTT_EVENT_DISCONNECTEDD

What can be the possible reason?

**Comment by tuanpmt** [comment]
Could you please help me test the lastest commit from master?

**Comment by Kasuhikdas** [comment]
sure will test and let you know.

**Comment by david-cermak** [comment]
Hi @Kasuhikdas 

Any update?

**Comment by Kasuhikdas** [comment]
That was a certificate issue. Working absolutely fine.
