### ISSUE TITLE
Not connecting to SSL Broker 

### ISSUE THREAD

**Issue by AmrutaCh** [espressif/esp-mqtt#44]
Previously I had used your [esp8266 mqtt lib](https://github.com/tuanpmt/esp_mqtt) with a mosquitto server and it works very well.
However, this esp32 lib is failing to connect to the same server.
I am using [mosquitto server](https://mosquitto.org/man/mosquitto-tls-7.html) with tls version tlsv1.
No certificates are used on the client side, only username and password is used for authentication. 

We get the below error in server side:
>_error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number_

Below is my mosquitto.conf:
>port 1883
>listener 8883
>
>log_dest stdout
>log_type all
>
>allow_anonymous false
>password_file /etc/mosquitto/password.txt
>
>cafile /home/<user>/ca.crt
>certfile /home/<user>/server.crt
>keyfile /home/<user>/server.key
>tls_version tlsv1

Any insights or suggestions

**Comment by david-cermak** [comment]
Hi @AmrutaCh 

Can you please test it with current version of the library? My mosqutto configuration looks similar
```
port 8883
cafile /home/david/ssl/mosq_certs/ca.crt
certfile /home/david/ssl/mosq_certs/server2.crt
keyfile /home/david/ssl/mosq_certs/server.key
require_certificate true
use_identity_as_username true
tls_version tlsv1
```
and esp client connects correctly, no issue with `tlsv1`

**Comment by AmrutaCh** [comment]
I don't remember now what was the issue. But I had got it working.
