### ISSUE TITLE
Accessing variables for ESP mqtt client struct in the callback functions

### ISSUE THREAD

**Issue by asadislam94** [espressif/esp-mqtt#55]
Hi,
It might be that my coding style is bad or maybe its some other reason, but I have to get access to the variables in the esp_mqtt_client because I pass that variable around in my functions and use the user context to differentiate between the multiple clients running. 
If I compile the library in current form, the linker gives me an error, as it doesnt have access to .c file where that structure is declared.
Is there any reason why you would want the application code to have access to that structure?

**Comment by tuanpmt** [comment]
Hi @asadislam94 

There are a `.user_context` can be pass to mqtt_client 

https://github.com/tuanpmt/espmqtt/blob/master/include/mqtt_client.h#L75

and get from:

https://github.com/tuanpmt/espmqtt/blob/master/include/mqtt_client.h#L44
