### ISSUE TITLE
esp_mqtt_client_stop()  stuck in xEventGroupWaitBits

### ISSUE THREAD

**Issue by stewy42** [espressif/esp-mqtt#62]
esp_mqtt_client_stop() should only call xEventGroupWaitBits   if client->state =   indicates  started

**Comment by david-cermak** [comment]
Hi @stewy42 ,

You are correct. 
A fix has been prepared in the idf. The related update of `esp-mqtt` will be on an `idf` branch, but soon to be merged to `master` (once IDFv3.2 is released).

Best Regards,
David

**Comment by stewy42** [comment]
Hi @david-cermak 

  Fix looks great

Thanks  
Stewart

**Comment by david-cermak** [comment]
Closed via https://github.com/espressif/esp-mqtt/commit/e26764502a108d2ad618e385362163082e418844
