### ISSUE TITLE
Doc request: Fields set in esp_mqtt_event_t by event_id type

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-mqtt#66]
I'm loving this package.  Kudos to you my friend.

I'm wondering if we can have some deeper docs / richer documentation on which fields are set in the esp_mqtt_event_t as a function of the event_id?

**Comment by david-cermak** [comment]
Resolved via https://github.com/espressif/esp-mqtt/commit/85f2eddabd80152264dd7362c8219306df3314ef
