### ISSUE TITLE
mbedtls_sha1' is deprecated

### ISSUE THREAD

**Issue by nicola-lunghi** [espressif/esp-mqtt#68]
components/espmqtt/lib/transport_ws.c: In function 'ws_connect':
components/espmqtt/lib/transport_ws.c:101:5: warning: 'mbedtls_sha1' is deprecated [-Wdeprecated-declarations]
     mbedtls_sha1(client_key_b64, (size_t)key_len, valid_client_key);
     ^
In file included from components/espmqtt/lib/transport_ws.c:10:0:
esp-idf/components/mbedtls/mbedtls/include/mbedtls/sha1.h:300:25: note: declared here
 MBEDTLS_DEPRECATED void mbedtls_sha1( const unsigned char *input,

**Comment by david-cermak** [comment]
Hi Nicola,

it was already fixed on an `idf` branch, but will be merged to master once IDFv3.2 is released.

Latest IDF already refers to the fixed `esp-mqtt`, so if you can please check the `esp-idf` master (no need to add `esp-mqtt`) and see the issue fixed, might you help closing this issue, please?

Thank you,
David
