### ISSUE TITLE
msg_id not consistent over multiple MQTT_EVENT_DATA events

### ISSUE THREAD

**Issue by OscarStarink** [espressif/esp-mqtt#70]
When receiving MQTT messages bigger then the receive buffer, one would expect multiple `MQTT_EVENT_DATA` events with the same `msg_id` and an increasing `current_data_offset`.

However only the first `MQTT_EVENT_DATA` event contains the correct `msg_id`, subsequent events contain a corrupted `msg_id`.

The issue is that `esp_mqtt_dispatch_event()` overwrites `msg_id` cause it assume that `in_buffer` contains a MQTT message with header. This is not the case when `deliver_publish()` requires additional `transport_read()` calls when it is receiving messages bigger then the read buffer.

**Comment by david-cermak** [comment]
Resolved in https://github.com/espressif/esp-mqtt/commit/06fe5cca8ed78dc5922cff5c406214b244b35a26
