### ISSUE TITLE
Compatible with the ESP8266 RTOS V3.X (IDFGH-1751)

### ISSUE THREAD

**Issue by xiongyumail** [espressif/esp-mqtt#73]
This is a great mqtt library， there are any plan for compatible with the ESP8266 RTOS V3.X?

**Comment by cgawron** [comment]
I'm just trying to fix the incompatibilities - does not look too complicated.

**Comment by cgawron** [comment]
See PR #76

**Comment by xiongyumail** [comment]
Thank you very much for your excellent work, I will test it and help push it into the SDK.

**Comment by lrusnac** [comment]
hey, will this get merged at some point? Curious if anybody tested it

**Comment by cgawron** [comment]
@lrusnac Actually the latest ESP8266 RTOS SDK contains both [esp-mqtt](https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/components/mqtt/esp-mqtt) and ibm-mqtt.

**Comment by Alvin1Zhang** [comment]
@cgawron Thanks for the notes. @lrusnac ESP8266 SDK already included [ESP-MQTT](https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/components/mqtt/esp-mqtt). Thanks.

**Comment by david-cermak** [comment]
Closing this older issue since the ESP8266 SDK includes esp-mqtt
