### ISSUE TITLE
publish 924 bytes, sent 171 bytes.

### ISSUE THREAD

**Issue by zhaochengwei** [espressif/esp-mqtt#86]
![image](https://user-images.githubusercontent.com/13081827/48177536-0ecced00-e350-11e8-80af-7799b576dfee.png)
![image](https://user-images.githubusercontent.com/13081827/48177547-1c827280-e350-11e8-8ba7-04f3e40d5bd0.png)

![image](https://user-images.githubusercontent.com/13081827/48177563-3328c980-e350-11e8-9641-74a55ecf90e0.png)

I publish 924 bytes，But just sent 171 bytes. I check my string and all is json format.How can I solve the problems.

**Comment by david-cermak** [comment]
Hi @zhaochengwei 

Sorry for such a late reply, are you still having this issue?
Which version of `esp-mqtt` you use?

**Comment by david-cermak** [comment]
Closing for no feedback. Please feel free to reopen!
