### ISSUE TITLE
MQTT_EVENT_DISCONNECTED reason

### ISSUE THREAD

**Issue by InfiniteYuan1** [espressif/esp-mqtt#99]
In our application we use mqtt over ssl to connect to the MQTT broker, so we use cert and client cert to mutual authentication.

this is a example cfg for esp_mqtt_client_init:

we are able to import our certificate and connect to the broker with the esp_mqtt_client library, we know only if the connection was complete successfully or not, but for error management we want know the reason when it fail the mqtt connection.

**Comment by david-cermak** [comment]
Hi @InfiniteYuan1 

I think it's a duplicate of https://github.com/espressif/esp-mqtt/issues/94
We will try to address the issue soon.

**Comment by david-cermak** [comment]
Closing as duplicate of https://github.com/espressif/esp-mqtt/issues/94 (Resolved)
